### ISSUE TITLE
Plugman Reload后插件报错

### ISSUE THREAD

**Issue by Msyial** [CarmJos/MoeTeleport#2]
问题简述
使用Plugman的Reload后插件报错

问题来源
1.输入/Plugman reload MoeTeleport
2.Plugman显示重载完成
3.输入插件指令发生报错

预期结果
正常重载 

截图
![EN56S3IIDR8IIVS{K O(JM6](https://user-images.githubusercontent.com/61540044/154676600-712e4a72-c11c-4726-bcd9-62f9ebc5a2d9.png)
![T5MWITBBU7LX9{)8JBJETLB](https://user-images.githubusercontent.com/61540044/154676762-a4f7c4f6-0a5e-47af-b49b-6fbd18f79a65.png)

**Comment by CarmJos** [comment]
您好，已于 [1.2.0](https://github.com/CarmJos/MoeTeleport/releases/tag/1.2.0) 版本修复，请下载使用。
