### ISSUE TITLE
玩家可以给自己发送传送请求

### ISSUE THREAD

**Issue by Msyial** [CarmJos/MoeTeleport#5]
玩家可以给自己发送一个Tp请求

**Comment by CarmJos** [comment]
您好，问题已定位，请下载 [**runs@1891853273**](https://github.com/CarmJos/MoeTeleport/actions/runs/1891853273) 的构件帮助测试问题是否已经解决，感谢您的支持！

**Comment by Msyial** [comment]
测试没问题了，谢谢！
