### ISSUE TITLE
多数据源读取支持

### ISSUE THREAD

**Issue by fyxrim** [CarmJos/MoeTeleport#6]
**功能简述**
希望支持ess数据

**需求来源**
希望支持ess数据

**功能参考**(可选)
无

**附加内容**
无

**Comment by CarmJos** [comment]
是要支持ESS数据的导入还是说支持直接读取玩家ESS的数据呢？

**Comment by fyxrim** [comment]
> 是要支持ESS数据的导入还是说支持直接读取玩家ESS的数据呢？
第二个

**Comment by fyxrim** [comment]
我要那个home功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CarmJos/MoeTeleport] 希望支持ess数据 (Issue #6)





 
我感觉如果有ESS的话，直接用ESS的tpa功能就可以了呀。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CarmJos** [comment]
ess好像也有home功能吧，也可以直接用唉。

**Comment by fyxrim** [comment]
那行吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 下午4:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CarmJos/MoeTeleport] 希望支持ess数据 (Issue #6)





 
ess好像也有home功能吧，也可以直接用唉。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CarmJos** [comment]
好像ess的home没有点击传送之类的吧？是想要这样的功能才需要支持ess数据的吗？

如果是的话，我会在后续支持 2~3 中存储格式，分别为 `YAML` 、`JSON` 、`MySQL/MariaDB` 与 `Essentials` ，请稍待我后续更新。

**Comment by fyxrim** [comment]
是的,我想要这样功能,好的 辛苦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CarmJos/MoeTeleport] 希望支持ess数据 (Issue #6)





 
好像ess的home没有点击传送之类的吧？是想要这样的功能才需要支持ess数据的吗？
 
如果是的话，我会在后续支持 2~3 中存储格式，分别为 YAML 、JSON 、MySQL/MariaDB 与 Essentials ，请稍待我后续更新。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CarmJos** [comment]
您好，您的需求已开发完成并通过测试，请下载 [runs@](https://github.com/CarmJos/MoeTeleport/actions/runs/1895534302) 的构件，帮助我进行二次测试，谢谢！

### 如何改为通过Essentials存储、读取数据
在插件配置文件中，找到 `storage.method`，并将其修改为 “essential”，如下所示：

```yaml
# 存储相关配置
storage:
  # 存储方式，可选 [ yaml | json | mysql(跨服推荐) | Essential(须安装ess插件) ]
  method: Essential
```

**Comment by CarmJos** [comment]
您好，您的需求已开发完成并通过测试，请下载 [**runs@1895563781**](https://github.com/CarmJos/MoeTeleport/actions/runs/1895563781) 的构件，帮助我进行二次测试，谢谢！

### 如何改为通过Essentials存储、读取数据
在插件配置文件中，找到 `storage.method`，并将其修改数值为 “`essential`”，如下所示：

```yaml
# 存储相关配置
storage:
  # 存储方式，可选 [ yaml | json | mysql | Essential(须安装ess插件) ]
  method: Essential
```

**Comment by CarmJos** [comment]
若您测试后未发现问题，且本需求已实现，请关闭本议题。

**Comment by CarmJos** [comment]
希望您能给我的MCBBS帖子评个分，人气是免费的，感谢您的支持！

**Comment by CarmJos** [comment]
您好，您的需求已在 [v3.0.0](https://github.com/CarmJos/MoeTeleport/releases/tag/3.0.0) 更新中实现，请您下载后备份并重命名旧的`messages.yml`与`config.yml`以便插件生成新配置文件。感谢您的支持！
