### ISSUE TITLE
玩家可自设的“WarpList”，可以通过权限设置每个玩家最多设置的数量，并提供/listwarps查询指令

### ISSUE THREAD

**Issue by Msyial** [CarmJos/MoeTeleport#7]
**功能简述**
玩家可自设的“WarpList”，可以通过权限设置每个玩家最多设置的数量，并提供/listwarps查询指令

**需求来源**
便于玩家使用

**功能参考**(可选)
类似于essentialsx

**Comment by CarmJos** [comment]
![image](https://user-images.githubusercontent.com/36306882/155746021-6b46fb00-3aac-4e3a-a208-c7b9bd36ae7e.png)

**Comment by CarmJos** [comment]
您好，您的需求已在 [v3.1.0](https://github.com/CarmJos/MoeTeleport/releases/tag/3.1.0) 更新中实现，请您下载后备份并重命名旧的messages.yml与config.yml以便插件生成新配置文件。感谢您的支持！
